serve:
  name: "YellowWenJie"
  mode: "release"
  port: 8081
  version: "v0.0.1"
  start_time: "2022-07-07"
  token_expire_time: 18000 # JWT token 过期时间（单位：秒）

mysql:
  host: "106.55.4.201"
  port: 3306
  user: "root"
  password: "huangwenjie"
  dbname: "Yellowwenjie"
  max_idle_conn: 10 # 最大空闲连接数
  max_open_conn: 20 # 最大打开连接数
